.MODEL SMALL
.STACK 100H
.DATA  
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV CX,49 ;COUNTER FOR LOOP 
    MOV AX,1  ;ADDS THE SUM OF SERIES AND STORE THE RESULT
    MOV BX,1 ;USED TO MOVE THE SERIES 3 STEPS FORWARD 
 L:
   ADD AX,BX
   ADD BX,3
   LOOP L
EXIT:
    INT 21H
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN